# -*- mode: ruby -*-
# # vi: set ft=ruby :

Vagrant.configure(2) do |config|

	#setting up the synced shared folder
	config.vm.synced_folder "shared", "/tmp/shared"

	#create 3 virtual computers 
	(1..3).each do |i|
		config.vm.define "agent#{i}" do |agent|
		
			# Selecting the box to use
			agent.vm.box = "chad-thompson/ubuntu-trusty64-gui"
		
			# Setting up the network options
			agent.vm.network "public_network", :public_network=> "wlan0",ip:"192.168.1.9#{i}"
			
			#calling the provision bash file
			config.vm.provision :shell, path:"bootstrap_base.sh"

			if i ==1
				config.vm.provision "master", type: "shell", path:"bootstrap_m.sh"
				config.vm.hostname = "master.local"
				
				#forward port from guest to host, this one can be used for jenkins
				config.vm.network "forwarded_port", guest: 80, hosst: 8080

			else
				config.vm.hostname = "agent#{i}.local"
				config.vm.provision "agent", type: "shell", path:"bootstrap_a.sh"
				
				##getting the agent to ssh into master and sign its certificate 
#				config.vm.provision "shell", inline: <<-EOC
#				echo "sining certificate"
#				#ssh into the master
#				sshpass -p "vagrant" ssh -o StrictHostKeyChecking=no vagrant@"192.168.1.91" << EOF
#					sudo puppet cert list
#					sudo puppet cert sign agent#{i}.local
#					sudo puppet cert list
#					exit 0
#					EOF	
#				EOC
				
				## to provision the agents with all things defined in site.pp, useful if you want to puppet to provision
				## straight away instead of waiting for the default 20 minute				
#				config.vm.provision :puppet do |puppet|
#					puppet.manifests_path = "shared/puppet/manifests"
#					puppet.manifest_file = "site.pp"
#					puppet.module_path = "shared/puppet/modules"
#				end
			end
			
			#configuring vm provider options
			agent.vm.provider "virtualbox" do |agentVM|
			
				agentVM.gui = true
				agentVM.name="PuppetAgent#{i}"
				
				#Setting the amount of RAM the VM has access to
				if i == 1
					agentVM.memory ="2048"
				else 
					agentVM.memory ="4096"
				end
				agentVM.cpus ="2"
			end
	    end	
	end
end
