#!/usr/bin/ruby
 
require 'openssl'
 
def parse_extensions(extension_request)
  extension_request_hash = {}
  extension_request.each do |extension|
    extension_request_hash[extension.value[0].value] = extension.value[1].value
  end
  return extension_request_hash
end
 
$csr = File.open("/var/lib/puppet/ssl/ca/requests/#{ARGV[0]}.pem").read
$valid_values = ['r8h4598u05jhfrij']
$extensions_hash = {}
request = OpenSSL::X509::Request.new $csr
 
request.attributes.each do |attribute|
  attr = OpenSSL::X509::Attribute.new attribute
  $extensions_hash = parse_extensions(attr.value.value.first.value)
end
 
exit 1 if ! $valid_values.include? $extensions_hash['1.3.6.1.4.1.34380.1.2.1.1.1']
